{
 "title": "Custom Exporter",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "metric",
    "label": "Select metric",
    "query": "weather_temperature_celsius,weather_humidity_percent,weather_pressure_hpa,weather_wind_speed_mps\n"
   }
  ]
 },
 "panels": [
  {
   "title": "Heat map of temperature",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "weather_temperature_celsius", "legendFormat": "Temparature" }
   ]
  },
  {
   "title": "Average temp (last 30 min)",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "avg_over_time(${metric}[30m])", "legendFormat": "Temparature" }
   ]
  },
  {
   "title": "Visibility",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "weather_visibility_m", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Daylight Hours",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(weather_sunset_unix - weather_sunrise_unix)/3600",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cloudiness",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "weather_cloudiness_percent", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Pressure",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "weather_pressure_hpa", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Wind Speed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(weather_wind_speed_mps[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Humidity %",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    { "expr": "avg_over_time(${metric}[5m])", "legendFormat": "Average Humidity" }
   ]
  },
  {
   "title": "Feels Likw",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "weather_feels_like_celsius", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    { "expr": "${metric}\r\n", "legendFormat": "Astana" }
   ]
  }
 ]
}