{
 "title": "Database Exporter Dashboard",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "database",
    "query": {
     "query": "label_values(pg_database_size_bytes, datname)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Total Number of Tables and Rows",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pg_table_info_table_count\r\n", "legendFormat": "{{datname}}" },
    { "expr": "pg_table_info_total_rows\r\n", "legendFormat": "Total Rows" }
   ]
  },
  {
   "title": "Users with Login Privileges",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_user_privileges_total_users\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Query Processing Speed (QPS)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(pg_query_qps_total_queries[5m])\r\n",
     "legendFormat": "{datname=\"$database\"}"
    }
   ]
  },
  {
   "title": "Cache Hit Ratio (%)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(rate(pg_stat_database_blks_hit[5m]) / (rate(pg_stat_database_blks_hit[5m]) + rate(pg_stat_database_blks_read[5m]))) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Connections",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pg_stat_activity_count{state=\"active\"})\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Idle Connections",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pg_stat_activity_count{state=\"idle\"})\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uptime (hours)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum_over_time(up{job=\"postgres\", instance=\"postgres_exporter:9187\"}[24h]) * (15 / 3600)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Connections",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pg_stat_activity_count)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tuples Inserted / sec",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(pg_stat_database_tup_inserted[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Database Size (GB)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_database_size_bytes{datname=\"$database\"} / 1024 / 1024 / 1024\r\n",
     "legendFormat": "{datname=\"$database\"}"
    }
   ]
  },
  {
   "title": "Deadlocks/min",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(pg_stat_database_deadlocks[5m]) * 60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tuple Fetch/Return Ratio",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "expr": "rate(pg_stat_database_tup_fetched[5m]) / rate(pg_stat_database_tup_returned[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transactions/sec (Rollback)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "rate(pg_stat_database_xact_rollback{datname=\"valorant_tournament\"}[5m])\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transactions/sec (Commit)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "targets": [
    {
     "expr": "rate(pg_stat_database_xact_commit[5m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}