{
 "title": "Node Exporter Dashboard",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(windows_cpu_time_total, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Number of processes",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "windows_system_processes\r\n", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "CPU Usage (%)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(windows_cpu_time_total{mode=\"idle\"}[5m])) * 100)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU usage (per core)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * sum by (core)(\r\n  rate(windows_cpu_time_total{mode!=\"idle\"}[5m])\r\n)\r\n/\r\nsum by (core)(\r\n  rate(windows_cpu_time_total[5m])\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU frequency / performance",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * rate(windows_cpu_processor_utility_total[5m]) \r\n/    rate(windows_cpu_processor_rtc_total[5m])\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network traffic — in/out (Mbit/sec)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "8 * rate(windows_net_bytes_received_total{nic=\"MediaTek Wi-Fi 6 MT7921 Wireless LAN Card\"}[5m]) / 1e6\r\n",
     "legendFormat": "In"
    },
    {
     "expr": "8 * rate(windows_net_bytes_sent_total{nic=\"MediaTek Wi-Fi 6 MT7921 Wireless LAN Card\"}[5m]) / 1e6",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "System uptime (hours)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(time() - windows_system_boot_time_timestamp) / 3600\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Load average",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "avg_over_time(windows_system_processor_queue_length[1m])\r\n\r\n",
     "legendFormat": "For 1 min"
    },
    {
     "expr": "avg_over_time(windows_system_processor_queue_length[5m])\r\n",
     "legendFormat": "For 5 min"
    },
    {
     "expr": "avg_over_time(windows_system_processor_queue_length[15m])",
     "legendFormat": "For 15 min"
    }
   ]
  },
  {
   "title": "Free disk space (GB)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "windows_logical_disk_free_bytes{volume=~\"C:|D:\"} / 1024^3\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM usage (%)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (1 - windows_memory_available_bytes / windows_memory_physical_total_bytes)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total / Available / Used Memory (GB)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "windows_memory_physical_total_bytes / 1024^3\r\n",
     "legendFormat": "Total Memory"
    },
    {
     "expr": "windows_memory_available_bytes / 1024^3",
     "legendFormat": "Available Memory"
    },
    {
     "expr": "(windows_memory_physical_total_bytes - windows_memory_available_bytes) / 1024^3",
     "legendFormat": "Used Memory"
    }
   ]
  },
  {
   "title": "Disk I/O (Read & Write Rate)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "rate(windows_logical_disk_read_bytes_total{volume=\"C:\"}[5m])\r\n",
     "legendFormat": "Read"
    },
    {
     "expr": "rate(windows_logical_disk_write_bytes_total{volume=\"C:\"}[5m])\r\n",
     "legendFormat": "Write"
    }
   ]
  }
 ]
}